tab_spaces = 4
max_width = 100
comment_width = 100
doc_comment_code_block_width = 100
fn_call_width = 100
fn_args_layout = "Tall"
fn_params_layout = "Tall"
indent_style = "Block"
imports_indent = "Block"
imports_layout = "Vertical"
newline_style = "Unix"
trailing_comma = "Vertical"
type_punctuation_density = "Wide"
error_on_line_overflow = true
error_on_unformatted = true
format_code_in_doc_comments = true
format_strings = true
hard_tabs = false
normalize_comments = true
normalize_doc_attributes = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
wrap_comments = true
trailing_semicolon = true
ignore = []